package server.command_executors;

public enum MethodType {
    LOGIN, LOGOUT,
    ADD_EMP, REMOVE_EMP, GET_INVENTORY_BY_BRANCH, SALE_PRODUCT,
    ADD_CUSTOMER, DELETE_CUSTOMER, GET_ALL_CUSTOMERS,OPEN_CHAT,
    SHOW_SALES_BY_PRODUCT, SHOW_SALES_BY_BRANCH, SHOW_SALES_BY_DATE,
    SHOW_BRANCH_EMPLOYEE, ADD_PRODUCT_TO_BRANCH


}
