package server.command_executors;

public enum MethodType {
    LOGIN, LOGOUT,
    ADD_EMP, REMOVE_EMP,
    GET_INVENTORY_BY_BRANCH, SALE_PRODUCT,
    ADD_CUSTOMER, DELETE_CUSTOMER, GET_ALL_CUSTOMERS,

    WAITING_FOR_CHAT_REQUEST,IS_SHIFT_MANAGER,GET_BRANCH_ID,
    REMOVE_FROM_WAITING_LIST, REMOVE_FROM_AVAILABLE_LIST,
    GET_ALL_EMP, IS_EMPLOYEE_EXISTS, GET_OPTIONAL_CHAT, AVAILABLE_FOR_CHAT_REQUEST, JOIN_EXIST_CHAT, START_CHAT_MESSAGE, CLOSE_CHAT, SEND_MESSAGE,
    OPEN_CHAT,
    EDIT_EMP,
    SHOW_SALES_BY_PRODUCT,
    SHOW_SALES_BY_BRANCH,
    SHOW_SALES_BY_DATE,
    SHOW_BRANCH_EMPLOYEE,
    ADD_PRODUCT_TO_BRANCH
}
