package client.serverCommunication;

public enum ClassType {
    EMPLOYEE, INVENTORY, PURCHASE_HISTORY, CUSTOMER, CHAT, LOGGER, EMPTY, EXCEPTION, SUCCESS, OBJECT
    // EMPLOYEE, INVENTORY, PURCHASE_HISTORY, CUSTOMER_NEW, CUSTOMER_REGULAR, CUSTOMER_VIP, CUSTOMER, EXCEPTION, CHAT; 
}
